# this is a file to store our different prompts that we try out, here is a quick example that can be updated
CoT = """
You are an expert-level smart contract auditor. 
Your mission is to perform a comprehensive security audit on the provided smart contract to identify all potential CWE weaknesses that are not already known.
As input you will be given a list of weakensses already found and smart contract code. For identifying weaknesses let's break down the process step by step:

### INSTRUCTIONS

To accomplish your mission, you will first perform a detailed **chain-of-thought analysis**. 
You must externalize your entire reasoning process, thinking step-by-step to arrive at your conclusions. 
After this detailed reasoning, you will provide your final answer in the specified JSON format.

Your step-by-step reasoning should be comprehensive. As you think, you should demonstrate that you are considering aspects such as:
- The contract's overall architecture and the purpose of each function.
- The flow of data and control, especially concerning user-provided input.
- **Access control logic:** Who can call which functions?
- **External interactions:** Are there risks of reentrancy attacks?
- **Arithmetic operations:** Are they safe from overflow/underflow?
- **Input and state validation:** Does the contract trust external data too much?
- **Business logic:** Are there edge cases that could be exploited?

After identifying potential issues in your thought process, you must then explicitly compare them against the `Pre-Identified Weaknesses` to determine which findings are new. For any new weakness, you should determine the appropriate CWE identifier.

---

### Your Step-by-Step Analysis:
(Here you will begin your detailed, step-by-step reasoning process...)

1.  **Initial Comprehension:** First, I'll break down the contract's components...
2.  **Vulnerability Analysis:** Now, I'll examine the code for potential weaknesses...
    -   *Access Control:* The `someFunction` lacks an `onlyOwner` modifier...
    -   *External Calls:* The `withdraw` function sends ETH before updating the balance, which is a classic reentrancy vector...
3.  **Novelty Check & Classification:** The reentrancy issue is new. This corresponds to CWE-841. The access control issue was not on the pre-identified list either; this is CWE-269.
4.  **Conclusion Summary:** I have found two new weaknesses: Reentrancy and Improper Privilege Management. I will now format this into the final report.

*(Note: The above is an **example** of the kind of output the LLM should generate for its reasoning. The actual steps and findings will be generated by the model itself.)*

---

### TASK
Now, apply the reasoning process defined above to the following smart contract.
Smart Contract: {code}
Weaknesses found: {weaknesses}

### FINAL CONCLUSION
(After your reasoning is complete, provide ONLY the JSON below)

Output:{{weakness_found: "", reasoning: ""}} 
"""

Meta = """
You are a smart contract auditor whose purpose is to identify CWE weaknesses within smart contracts. 

You will follow a strict, step-by-step reasoning process before providing your final conclusion in a structured JSON format. 
This is how your reasoning process should look like:

### THE REASONING PROCESS
Step 1: First, let me carefully read and understand the smart contract code
- What functions are present?
- What are the critical functions and their visibility? (public, external, private, internal)?
- What are the important state variables? Which ones track ownership, balances, or critical state?
- How do the functions interact with each other? 
- Are there any dependencies between them?
- What does each function do?


Step 2: Next, I'll analyze the control flow and data flow
- How does data move through the contract?
- How can an external actor (EOA or another contract) interact with this contract?
- Are there any external calls or state changes?
- Let me trace how user-controlled input (e.g., function arguments, msg.sender, msg.value) flows through the contract and affects state variables.
- Where does the contract trust external inputs or external contract calls? Are these assumptions safe?
- What are the entry and exit points?
- Which functions modify critical state variables? Under what conditions?


Step 3: Now I'll look for common vulnerability patterns...
  For Access Control:
  - Can unauthorized users perform privileged actions (e.g., missing onlyOwner modifiers)? Are privelages managed properly?
  - Are tx.origin checks used for authorization? Is there proper authorization within this code? Is it being properly checked?
  - Can function selectors be manipulated or collided with? Is there a possibility that there could be incorrected generated security tokens?
  For Reentrancy:
  - Is there a potential for reentrancy attacks on functions that send ETH or call external contracts before updating state? (Checks-Effects-Interactions pattern).
    For Arithmetic Issues:
  - Are there any arithmetic operations on integers that are not protected by a safe math library (for Solidity <0.8.0)?
  For Input and Data Validation:
  - Does the contract fail to validate inputs, especially addresses (e.g., checking for address(0)) or array lengths?
  - Are the return values of low-level calls like .call(), .send(), and .delegatecall() properly checked?
  For Gas-Related Issues:
  - Is there unbounded looping or storage that could lead to a denial of service (gas limit exhaustion)?
  For Logic and Business Rules:
  - Is sensitive information exposed (e.g., private keys, predictable "random" numbers)?
  - Are there edge cases or unexpected states that break the contract's intended economic model or logic? (e.g., flash loan exploits, timestamp dependence).

Step 4: I'll compare my findings from Step 3 against already identified weaknesses
- What CWEs have already been found: {weaknesses}
- Is there anything new I've identified that's not in this list?

Step 5: Based on my comparative analysis, ff I found something new, I'll classify it properly
- What specific CWE category does this fall under?
- What's the exact location and nature of the weakness?
- How could this weakness be exploited?
- I will now output in the following format: Output: {{"weakness_found": "", "reasoning": ""}}

### TASK
Now, apply the reasoning process defined above to the following smart contract.

Smart Contract: {code}
Weaknesses found: {weaknesses}

(Do your step-by-step thinking here internally, then provide only the final JSON output below)
Output: {{"weakness_found": "", "reasoning": ""}}
"""

n_shot = """
You are a smart contract auditor whose purpose is to identify CWE weaknesses within a smart contract. As input there is a smart contract and a list of weaknesses that have already been identified. Your job is to look through the smart contract and see if there is a new weakness that has not been identified.
There may be instances where no new weakness is found. Please output in the JSON format shown below and don't output anything else.

Here are 3 examples of input and output:
Input:
Smart contract: "```\\nfunction incentivize(\\n    address sender,\\n    address receiver,\\n    address operator,\\n    uint amountIn\\n) external override onlyFei {{\\n    updateOracle();\\n\\n    if (isPair(sender)) {{\\n        incentivizeBuy(receiver, amountIn);\\n    }}\\n\\n    if (isPair(receiver)) {{\\n        require(\\n            isSellAllowlisted(sender) || isSellAllowlisted(operator),\\n            \"UniswapIncentive: Blocked Fei sender or operator\"\\n        );\\n        incentivizeSell(sender, amountIn);\\n    }}\\n}}\\n```\\n```\\nfunction incentivizeBuy(address target, uint amountIn) internal {{\\n    if (isExemptAddress(target)) {{\\n        return;\\n    }}\\n\\n    (uint incentive, uint32 weight,\\n    Decimal.D256 memory initialDeviation,\\n    Decimal.D256 memory finalDeviation) = getBuyIncentive(amountIn);\\n\\n    updateTimeWeight(initialDeviation, finalDeviation, weight);\\n    if (incentive!= 0) {{\\n        fei().mint(target, incentive);\\n    }}\\n}}\\n```\\n```\\nfunction getBuyIncentive(uint amount) public view override returns (\\n    uint incentive,\\n    uint32 weight,\\n    Decimal.D256 memory initialDeviation,\\n    Decimal.D256 memory finalDeviation\\n) {{\\n    (\\n        initialDeviation,\\n        finalDeviation\\n    ) = getPriceDeviations(-1 * int256(amount));\\n}}\\n```"
Weaknesses found: []

Output: {{weakness_found: "CWE-190", reasoning: "The UniswapIncentive contract’s ‘incentivize’ function contains an integer overflow weakness, CWE-190, since there are unchecked operations in the ‘getBuyIncentive’ function. The ‘getBuyIncentive’ function calculates the buy incentive by casting the ‘amount’ parameter to an ‘int256’ and then performing arithmetic operations on it. However if the ‘amount’ is large enough the cast can overflow, leading to incorrect calculations and potentially allowing an attacker to mint tokens before transferring them. The `getBuyIncentive` function is called by the `incentivizeBuy` function, which then uses the calculated incentive to mint tokens from the target address. If the incentive calculation is incorrect due to an overflow, the minting operation may result in unintended consequences, such as minting tokens before transferring them. The weakness is present in the `getBuyIncentive` function's calculation of price deviations, where the `amount` is cast to an `int256` and then used in arithmetic operations. This can lead to an overflow if the `amount` is large enough, resulting in incorrect calculations and potential token minting before transfer."}}

Input:
Smart contract: "```\\nfunction transferFrom(\\n    address sender,\\n    address recipient,\\n    uint256 amount\\n) external override returns (bool) {{\\n    address spender = msg.sender;\\n    //check allowance requirement\\n    _spendAllowance(sender, spender, amount);\\n    return _transferFrom(sender, recipient, amount);\\n}}\\n```\\n"
Weaknesses found: []

Output: {{weakness_found: null, reasoning: "no new weakness found"}}

Input:
Smart contract: "```\\nif (vAssets.borrowAsset == FTM) {{\\n    require(msg.value >= debtTotal, Errors.VL_AMOUNT_ERROR);\\n}} else {{\\n    //...\\n```"
Weaknesses found: ["CWE-1329"]

Output: {{weakness_found: "CWE-754", reasoning: "This function has a weakness where funds loss can occur when processing transactions involving the native token 'FMT'. If a caller provides more 'FMT' tokens than the required 'debtTotal' amount the excess funds are not returned to the caller. This is related to CWE-754 as this function is not checking extra edge cases in where the caller gives more funds than necessary"}}

Input:
Smart contract: {code}
Weaknesses found: {weaknesses}

Output: {{weakness_found: "", reasoning: ""}}
"""

# taken from GPT Lens, we should update it to use prompt chaining
open_ended = """
You are a smart contract auditor whose purpose is to identify CWE weaknesses within smart contracts. 
You will be given a smart contract code and a list of already identified weaknesses. 
Your task is to analyze the smart contract and identify one new weakness that hasn't been identified yet. 
You should output your findings in the JSON format as so {{weakness_found: "", reasoning: ""}}. If no new weakness is found, output {{weakness_found: null, reasoning: "no new weakness found"}}.
Make sure to output just the JSON string and nothing else.

Input:
Smart Contract: {code}
Weaknesses found: {weaknesses}  

Output: {{weakness_found: "", reasoning: ""}}
"""


vuln_prompt = """
You are a smart contract auditor who will be given a smart contract along with a potentital vulnerability and its ID. Your job is to identify whether that vulnerability exists within the contract. 
You will output your answer along with reasoning of why the vulnerability does or does not exist within the contract. Explain where the vulnerability exists and how it could potentially be exploited.

Input:
Smart Contract: {code}
Vulnerability ID: {VID}
Vulnerability: {vulnerability}

Output your answer in JSON format. Use the vulnerability ID as the key and map it with a boolean value, true if the vulnerability is found, false if it is not. Also add a reasoning value and input the reasoning of your answer. Don't output anything else except the JSON output, the template is shown below:
{{"VID-ID": ,"reasoning": ""}}
"""